apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../..

# Flag 1: Add a suffix so it doesn't collide with other envs
nameSuffix: -dev

# Flag 2: Add a label for easy filtering
commonLabels:
  variant: development

# Flag 3: Small scale for Dev
patches:
- target:
    kind: Deployment
    name: nginx-deployment
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1